### ISSUE TITLE
export functions to the namespace

### ISSUE THREAD

**Issue by nikosbosse** [sbfnk/ebola.forecast.wa.sl#2]
the functions for the packages aren't exported to the NAMESPACE and therefore can't be used. 
Adding 
#' @export
to the roxygen comments of the functions should work

**Comment by sbfnk** [comment]
Closed via b3f9cda36bb187d29f22efbe820a34de48e2ea1a, 4230776cac38fc4bbbb27ee1553679ddf4edf34c and 1c9d62fc6794ec212f3d09790fb4c80a2e07050a
